from typing import Protocol


class CiphertextStorage(Protocol):
    def put_ciphertext(self, object_key: str, content: bytes, content_hash: str) -> dict: ...

    def get_ciphertext(self, object_key: str) -> bytes: ...

    def get_ciphertext_metadata(self, object_key: str) -> dict: ...

    def delete(self, object_key: str) -> None: ...
