"""create_auth_tables_official_diagram

Revision ID: 1b0bb087e678
Revises: 
Create Date: 2026-09-16 03:05:47.223754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b0bb087e678'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('id_permiso', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso')
    )
    op.create_index(op.f('ix_permiso_codigo'), 'permiso', ['codigo'], unique=True)
    op.create_table('rol',
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=True)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('correo_verificado', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_table('dispositivo',
    sa.Column('id_dispositivo', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('sistema_operativo', sa.String(length=100), nullable=True),
    sa.Column('identificador_seguro', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('es_confiable', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_revocacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revocado_por'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_dispositivo')
    )
    op.create_index(op.f('ix_dispositivo_identificador_seguro'), 'dispositivo', ['identificador_seguro'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.Column('id_permiso', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permiso.id_permiso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso')
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    op.create_table('evento_auditoria',
    sa.Column('id_evento', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.Column('id_dispositivo', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('resultado', sa.String(length=50), nullable=False),
    sa.Column('recurso_id', sa.String(length=255), nullable=True),
    sa.Column('recurso_tipo', sa.String(length=100), nullable=True),
    sa.Column('direccion_ip', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('detalles', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo.id_dispositivo'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('sesion',
    sa.Column('id_sesion', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_dispositivo', sa.UUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('revocada', sa.Boolean(), nullable=False),
    sa.Column('motivo_revocacion', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo.id_dispositivo'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_index(op.f('ix_sesion_refresh_token_hash'), 'sesion', ['refresh_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesion_refresh_token_hash'), table_name='sesion')
    op.drop_table('sesion')
    op.drop_table('evento_auditoria')
    op.drop_table('usuario_rol')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_dispositivo_identificador_seguro'), table_name='dispositivo')
    op.drop_table('dispositivo')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_permiso_codigo'), table_name='permiso')
    op.drop_table('permiso')
    # ### end Alembic commands ###
