"""create_mfa_and_recovery_tables

Revision ID: 88147b01c815
Revises: 1b0bb087e678
Create Date: 2026-09-16 04:11:55.227207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88147b01c815'
down_revision: Union[str, None] = '1b0bb087e678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autenticador_mfa',
    sa.Column('id_autenticador', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('secreto_cifrado', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('contador', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_autenticador')
    )
    op.create_table('recuperacion_cuenta',
    sa.Column('id_recuperacion', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('utilizado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_utilizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_recuperacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recuperacion_cuenta')
    op.drop_table('autenticador_mfa')
    # ### end Alembic commands ###
